### ISSUE TITLE
I get error

### ISSUE THREAD

**Issue by sbov** [mingyuyng/OFDM-guided-JSCC#2]
File "OFDM-guided Deep Joint Source Channel Coding/Deep-JSCC-for-images-with-OFDM-master/models/channel.py", line 189, in forward
    x = x.view(N, self.opt.P, (Ns+self.opt.N_pilot)*(self.opt.M+self.opt.K), 2)
RuntimeError: shape '[128, 1, 640, 2]' is invalid for input of size 81920

**Comment by SIN5t** [comment]
have you solve this now ? I met the same promblem, thanks!

**Comment by sbov** [comment]
I have just seen your email. The code had several issues that I addressed,
and the problems should be resolved now. If you are still facing any issues
with this code, please let me know.

**Comment by wzilu** [comment]
Hello! I need to study this project to complete my thesis, but I've encountered the same problem as you. Could you please tell me how you solved it?Thank you.
